[features]
seeds = false
skip-lint = false
[programs.localnet]
blocktip = "J12y7DHEGtNzGxWrW5cDNVdj546HgLkit89BSbfjcYoo"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/seanpe/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
