[features]
seeds = false
skip-lint = false
[programs.localnet]
blocktip = "AhXmrTCwoB2A1xBfSu6trRXysGvaaA485PY3sLQPUzhC"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/manoloenriquez/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
